# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Safe-Isa-XS`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

